meta_product_name: "Releasy"
meta_title: "Releasy - Follow your Favorites"
meta_description: "Follow your favorite creators and get notified when they release new content."
meta_image: "https://res.cloudinary.com/dcwt8cjne/image/upload/v1624434079/releasy_screen_s6syrb.jpg" # should exist in `app/assets/images/`
